on:
  push:
    branches:
      - master
    paths:
      - 'test/gcc-9-2-0/**'

jobs:
  run-verify:
    needs: publish
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run:  docker login -u spihill -p ${{ secrets.PACKAGES_LOGIN_TOKEN }} docker.pkg.github.com
    - name: Docker pull
      run: docker pull docker.pkg.github.com/spihill/docker-package-test/gcc-9.2.0:latest
    - name: verify test
      uses: ./test/gcc-9-2-0/
      with:
        CXX: g++