on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: docker-login
      env:
        user_name: ${GITHUB_ACTOR}
        token: ${{ secrets.PACKAGES_LOGIN_TOKEN }}
      run: docker login -u ${user_name} -p ${token}

