on:
  push:
    branches:
      - master
    paths:
      - 'gcc-5/**'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Build and publish
      uses: elgohr/Publish-Docker-Github-Action@2.12
      with:
        name: docker.pkg.github.com/spihill/docker-package-test/gcc-5
        username: spihill
        password: ${{ secrets.PACKAGES_LOGIN_TOKEN }}
        registry: docker.pkg.github.com
        workdir: gcc-5
