on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u spihill --password-stdin docker.pkg.github.com
    - name: Docker pull
      run: docker pull docker.pkg.github.com/spihill/docker-package-test/gcc-9.2.0:latest
    - name: verify test
      uses: ./test/gcc-9-2-0/
      with:
        CXX: g++