on:
  push:
    branches:
      - master
    paths:
      - 'verify-test'

jobs:
  publish:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Docker login
      run: docker login -u spihill -p ${{ secrets.GITHUB_TOKEN }} docker.pkg.github.com
    - name: Docker pull
      run: docker pull docker.pkg.github.com/spihill/docker-package-test/gcc-5:latest
    - name: verify test
      uses: ./
      with:
        YOUR_GITHUB_USER_NAME: spihill
        CLONE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        YOUR_GITHUB_REPOSITORY: library
        CXX: g++-5